export const UPDATE_BREADCRUMBS = 'UPDATE_BREADCRUMBS'
export const UPDATE_SIDENAV = 'UPDATE_SIDENAV'

//Products
export const SET_PRODUCTS = 'PRODUCTS_SET'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
